export { getAnthropicClient, callClaude } from './client';
export { parseTermSheet } from './pipelines/parse-term-sheet';
export type { TermSheetParseResult } from './pipelines/parse-term-sheet';
export { generateDocument } from './pipelines/generate-document';
export type { GenerateDocumentInput, GenerateDocumentResult } from './pipelines/generate-document';
export { generateDisclosureSchedules } from './pipelines/disclosure-generator';
export type { DisclosureScheduleExtraction, DisclosureGenerationResult } from './pipelines/disclosure-generator';
export { extractPositionsFromEmail } from './pipelines/position-extractor';
export type { ExtractedPosition, PositionExtractionResult } from './pipelines/position-extractor';
export { extractActionItems } from './pipelines/action-item-extractor';
export type { ExtractedActionItem, ActionItemExtractionResult } from './pipelines/action-item-extractor';
export { generateClientCommunication } from './pipelines/client-communication';
export type { ClientCommunicationInput, ClientCommunicationResult } from './pipelines/client-communication';
export { generateClosingChecklist } from './pipelines/closing-generator';
export type { ClosingConditionExtraction, ClosingDeliverableExtraction, ClosingGenerationResult } from './pipelines/closing-generator';
