export { getDriveClient, getRootFolderId } from './google-drive/client';
export { createDealFolderStructure } from './google-drive/folder-structure';
export { extractTextFromDocx, extractHtmlFromDocx } from './documents/docx-reader';
export { extractTextFromPdf } from './documents/pdf-reader';
export { generateDocxFromContent, generateDocxFromText } from './documents/docx-writer';
export { segmentDocument } from './documents/provision-segmenter';
export type { DocumentContent } from './documents/docx-writer';
export type { ProvisionSegment } from './documents/provision-segmenter';
export { identifyFirm } from './precedent/firm-identifier';
export type { FirmIdentificationResult } from './precedent/firm-identifier';
export { scoreFormulation } from './precedent/quality-scorer';
export type { QualityScores } from './precedent/quality-scorer';
export { searchPrecedent } from './precedent/quality-retrieval';
export type { PrecedentSearchParams, PrecedentResult } from './precedent/quality-retrieval';
