export { getDriveClient, getRootFolderId } from './google-drive/client';
export { createDealFolderStructure } from './google-drive/folder-structure';
export { extractTextFromDocx, extractHtmlFromDocx } from './documents/docx-reader';
export { extractTextFromPdf } from './documents/pdf-reader';
export { generateDocxFromContent, generateDocxFromText } from './documents/docx-writer';
export { segmentDocument } from './documents/provision-segmenter';
export type { DocumentContent } from './documents/docx-writer';
export type { ProvisionSegment } from './documents/provision-segmenter';
export { identifyFirm } from './precedent/firm-identifier';
export type { FirmIdentificationResult } from './precedent/firm-identifier';
export { scoreFormulation } from './precedent/quality-scorer';
export type { QualityScores } from './precedent/quality-scorer';
export { searchPrecedent } from './precedent/quality-retrieval';
export type { PrecedentSearchParams, PrecedentResult } from './precedent/quality-retrieval';
export { searchEdgar, downloadExhibit } from './precedent/edgar-discovery';
export type { EdgarSearchParams, EdgarFiling, EdgarExhibit } from './precedent/edgar-discovery';
export { ingestFromEdgar } from './precedent/edgar-ingestion';
export type { IngestionResult, IngestionConfig } from './precedent/edgar-ingestion';
export { updateQualityFromFeedback } from './precedent/quality-updater';
export type { QualityFeedbackEvent } from './precedent/quality-updater';
export { getGmailClient, resetGmailClient } from './gmail/client';
export { fetchRecentEmails, addLabel, getAttachmentData } from './gmail/fetch-emails';
export type { GmailMessage, GmailAttachment, FetchEmailsOptions } from './gmail/fetch-emails';
